### ISSUE TITLE
Agent needs to handle flipping back from a symmetric only node to an asymmetric node

### ISSUE THREAD

**Issue by nerdalert** [nexodus-io/nexodus#769] opened 2023-04-09 03:52 UTC
Currently when a node joins as `--relay-only` and then rejoins as a full mesh peer, the peers in the mesh still see it as a relay.

`ax.symmetricNat` needs to be updated in a reconcile method. It could be a symmetric nat check in a periodic stun reconcile once we merge stun based discovery.

**Comment by nerdalert** [comment] 2023-04-11 00:57
Thinking on this some more, if we give the agent the option to relay only, we need another ax receiver for scenarios where the symmetric nat is detected vs explicitly set. If it's symmetric NAT deteceted and then flips to an asymmetric NAT cone it should automatically flip. Personally, I like a relay only explicit set option that would always stay hub/spoke (for testing its handy as well).

**Comment by russellb** [comment] 2023-06-04 14:39
Closing as a duplicate of #423

**Closed** 2023-06-08 01:47 UTC
