### ISSUE TITLE
Beef up Symmetric NAT discovery on initialization

### ISSUE THREAD

**Issue by nerdalert** [nexodus-io/nexodus#1043] opened 2023-05-18 21:54 UTC
- Add a retry on initial symmetric NAT discovery. If there is a failed STUN lookup on initialization, we currently drop back to assuming the NAT is not symmetric. This will build peers with no connectivity since they cannot be hole-punched.
- Add a warning if there is no relay defined in the ORG that no connectivity is available until a relay is bootstrapped.

**Comment by russellb** [comment] 2023-06-04 14:50
This should be fixed by doing regular reconciliation on the NAT state and adjusting the configuration accordingly. I'm going to close this as a duplicate of #423, since that issue is generally about fixing changes between NAT types.

**Closed by russellb** 2023-06-04 14:50 UTC
Labels: bug, nexd
